import LeftSide from '@/components/LeftSide'
import Navbar from '@/components/Navbar'
import RigthSide from '@/components/RigthSide'
import Head from 'next/head'
import { motion } from "framer-motion"
import Banner from '@/components/Banner'
import About from '@/components/About'
import Experience from '@/components/Experience'
import Projects from '@/components/Projects'
import Achived from '@/components/Achived'
import Contact from '@/components/Contact'


export default function Home() {
  return (
    <>
      <Head>
        <title>Hasibul Hasan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-full h-screen bg-bodyColor text-textLigth overflow-x-hidden overflow-y-scroll font-bodyFont scrollbar scrollbar-track-textDark/20 scrollbar-thumb-textDark/60'>
        <Navbar />

        <div className='w-full h-[88vh] xl:flex justify-between items-center gap-20'>
          {/* left side */}
          <motion.div initial={{  opacity: 0 }}
            animate={{  opacity: 1 }}
            transition={{ delay: 1.5 }} className='hidden xl:inline-flex w-32 h-full fixed left-0 bottom-0'>
            <LeftSide />
          </motion.div>
          {/* middle side */}
          <div className=' h-[88vh] w-full mx-auto p-4 lgl:pl-24 ' >
           <Banner/>
           <About/>
            <Experience/>
             <Projects/>
             <Achived/>
             <Contact/>




          </div>
          {/* right side */}
          <motion.div initial={{  opacity: 0 }}
            animate={{  opacity: 1 }}
            transition={{ delay: 1.5 }} className='hidden xl:inline-flex w-32 h-full fixed right-0 bottom-0'>
            <RigthSide />
          </motion.div>
        </div>

      </main>
    </>
  )
}
